project:
  type: website
  output-dir: docs

website:
  title: "BIO511 Genomics - Practical Repository"
  description: "Practical exercises for the BIO511 Genomics course practical sections"
  navbar:
    background: light
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - sidebar:cli
      - sidebar:gwf
      - sidebar:python

  sidebar:
    - id: cli
      title: "Command Line Programming"
      style: docked
      background: light
      contents:
      - section: "Intro to Command Line"
        contents:
        - href: "practicals/Practicals - CLI/PRACTICAL_INTRO_TO_COMMAND_LINE.qmd"
          text: "Practical 1: CLI Basics"
        - href: "practicals/Practicals - CLI/PRACTICAL_SETTING_UP_THE_HPC.qmd"
          text: "Practical 2: Setting up the HPC"
        - href: "practicals/Practicals - CLI/PRACTICAL_WORKSPACE_MANAGEMENT.qmd"
          text: "Practical 3: Workspace Management and Data Management"
        - href: "practicals/Practicals - CLI/PRACTICAL_SCRIPTS_AND_ADVANCED_TEXT_MANIPULATION.qmd"
          text: "Practical 4: Scripting and Advanced Text Manipulation"
        - href: "practicals/Practicals - CLI/PRACTICAL_SOFTWARE_INSTALLATION_AND_CONTAINERS.qmd"
          text: "Practical 5: Software & Containers"
      - section: "Coding Best Practices"
        contents:
        - href: "practicals/Practicals - Git/PRACTICAL_GIT_SESSION1.qmd"
          text: "Practical 1: Git Fundamentals: Session 1"
        - href: "practicals/Practicals - Git/PRACTICAL_GIT_SESSION2.qmd"
          text: "Practical 2: Git Fundamentals: Session 2"
        - href: "practicals/Practicals - Git/PRACTICAL_BEST_CODING_PRACTISES.qmd"
          text: "Practical 3: Best Coding Practices"

    - id: gwf
      title: "Genomics Workflows"
      style: docked
      background: light
      contents:
      - href: "practicals/Practicals - WGS/PRACTICAL_RAWDATA_AND_QC.qmd"
        text: "Practical 1: Quality Control and Classification"
      - href: "practicals/Practicals - WGS/PRACTICAL_ASSEMBLY_AND_MAPPING.qmd"
        text: "Practical 2: Genome Assembly and Mapping"
      - href: "practicals/Practicals - WGS/PRACTICAL_FUNCTIONAL_ANNOTATION.qmd"
        text: "Practical 3: Genome Annotation"

    - id: python
      title: "Python Programming"
      style: docked
      background: light
      contents:
      - href: "practicals/Practicals - Python/PRACTICAL_SETUP.qmd"
        text: "Practical 0: Introduction"
      - href: "practicals/Practicals - Python/PRACTICAL_DATA_TYPES_AND_IF_ELSE.qmd"
        text: "Practical 1: Python Data Types and If/Else Clauses"
      - href: "practicals/Practicals - Python/PRACTICAL_LOOPING.qmd"
        text: "Practical 2: Python Loops"
      - href: "practicals/Practicals - Python/PRACTICAL_FUNCTIONS.qmd"
        text: "Practical 3: Python Functions"
      - href: "practicals/Practicals - Python/PRACTICAL_MODULES.qmd"
        text: "Practical 4: Python Modules"
      - href: "practicals/Practicals - Python/PRACTICAL_FILES.qmd"
        text: "Practical 5: Files"
      - href: "practicals/Practicals - Python/PRACTICAL_PLOTTING.qmd"
        text: "Practical 5: Plotting"

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    link-external-newwindow: true
    css: pages/styles.css
