---
title: "BIO511 Genomics - Practical Repository"
subtitle: "Welcome to the practical exercises for the BIO511 Genomics course"
author: "Tor Kling"
date: today
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    theme: cosmo
---

## Course Overview

This repository contains practical exercises for the BIO511 Genomics course. Use this page, or the navbar to navigate to the different sections. 

### 🖥️ Command Line Programming
Here are the practical exercises related to command line programming section of the course:

#### Introduction to Command Line Interface (CLI) and HPC
- **[Practical 1: CLI Basics](PRACTICAL_INTRO_TO_COMMAND_LINE.qmd)**
- **[Practical 2: Setting up the HPC](PRACTICAL_SETTING_UP_THE_HPC.qmd)**
- **[Practical 3: Workspace Management and Data Management](PRACTICAL_WORKSPACE_MANAGEMENT.qmd)**
- **[Practical 4: Scripting and Advanced Text Manipulation](PRACTICAL_SCRIPTS_AND_ADVANCED_TEXT_MANIPULATION.qmd)**
- **[Practical 5: Software & Containers](PRACTICAL_SOFTWARE_INSTALLATION_AND_CONTAINERS.qmd)**

#### Coding Best Practices
- **[Practical 1: Git Fundamentals: Session 1](PRACTICAL_GIT_SESSION1.qmd)**
- **[Practical 2: Git Fundamentals: Session 2](PRACTICAL_GIT_SESSION2.qmd)**
- **[Practical 3: Best Coding Practices for Command‑Line Programming](PRACTICAL_BEST_CODING_PRACTISES.qmd)**

### 🧬 Genomics Workflows
- **[Practical 1: Quality Control and Classification](PRACTICAL_RAWDATA_AND_QC.qmd)**
- **[Practical 2: Genome Assembly and Mapping](PRACTICAL_ASSEMBLY_AND_MAPPING.qmd)**
- **[Practical 3: Genome Annotation](PRACTICAL_FUNCTIONAL_ANNOTATION.qmd)**

### 🐍 Python Programming
*Coming Soon...*

---

*For questions or issues, please contact the course instructors.*